# Generated by Django 4.1.5 on 2023-01-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=30)),
                ("party", models.CharField(max_length=1)),
                ("district", models.IntegerField()),
                (
                    "lis_id",
                    models.CharField(max_length=5, verbose_name="LIS Member ID"),
                ),
                (
                    "lis_no",
                    models.CharField(max_length=5, verbose_name="LIS Member Number"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("lis_id", models.CharField(max_length=3, verbose_name="LIS ID")),
                ("year", models.IntegerField()),
            ],
        ),
    ]
