# Generated by Django 4.1.5 on 2023-01-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legislator",
            name="place",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
