# Generated by Django 4.1.5 on 2023-01-12 02:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_legislator_place"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("text", models.TextField()),
                ("d_introducted", models.DateField(verbose_name="Date Introduced")),
                ("emergency", models.BooleanField(default=False)),
                ("passed", models.BooleanField(default=False)),
                ("d_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="legislator",
            name="d_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="session",
            name="d_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="BillSummaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_id", models.CharField(max_length=10)),
                ("category", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("d_added", models.DateTimeField(auto_now_add=True)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="core.bill",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bill",
            name="patron",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="introduced",
                to="core.legislator",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="core.session",
            ),
        ),
    ]
