# Generated by Django 4.1.5 on 2023-01-12 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_bill_legislator_d_added_session_d_added_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="d_introducted",
            new_name="d_introduced",
        ),
    ]
