# Generated by Django 4.1.5 on 2023-01-16 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_rename_patron_bill_introduced_by_bill_sessions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="session",
        ),
        migrations.AddField(
            model_name="bill",
            name="patrons",
            field=models.ManyToManyField(through="core.Patron", to="core.legislator"),
        ),
        migrations.AlterField(
            model_name="patron",
            name="bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.bill"
            ),
        ),
        migrations.AlterField(
            model_name="patron",
            name="legislator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.legislator"
            ),
        ),
    ]
