# Generated by Django 4.1.5 on 2023-01-21 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_action_d_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="patron",
            name="d_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="legislator",
            name="district",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="legislator",
            name="party",
            field=models.CharField(max_length=1, null=True),
        ),
    ]
